### ISSUE TITLE
Prevent adding to schedule if there's a final exam clash

### ISSUE THREAD

**Issue by imtixz** [eniac00/prepre_reg#3]
I think the API data also has final exam dates. Pls either prevent adding to routine when exam clash happens or at least color code it so there's some way to know there's a final exam clash. Had exam clashes 2/3 times during advising this semester after using this tool to plan schedule. Would be very helpful if it automatically detected it and let me know earlier when I was still planning.

**Comment by eniac00** [comment]
Thank you for your suggestion Imtiaz. We will include the exam schedule in the next update Inshallah.
